import {
  ChesLogo,
  SVNITLOGO,
  aiche_logo,
  SIPHON,
  Workshop,
  car,
  K12,
  uphoto,
  Alchemy,
  aa,
  ab,
  ac,
  ad,
  ae,
  af,
  ag,
  Alchemylogo,
  SIPHONlogo,
  Workshoplogo,
  K12logo,
  Eurekalogo,
  car_logo,
  SRClogo,
  SRC,
  aneCar,
  alluCar,
} from "@/public/assets";

export const NavLinks = [
  {
    id: "/",
    title: "Home",
  },
  {
    id: "/#About",
    title: "About",
  },
  {
    id: "/Events",
    title: "Events",
  },
  {
    id: "/Achievement",
    title: "Achievements",
  },
  {
    id: "/Team",
    title: "Team",
  },

  {
    id: "/contact",
    title: "Contact",
  },
];

// export const Developers = [
//   {
//     id: 1,
//     name: "Archit ",
//     Linkedin: "https://www.linkedin.com/in/archit-kulshrestha-1aa01a255/",
//   },
//   {
//     id: 2,
//     name: "Aditya ",
//     Linkedin: "https://www.linkedin.com/in/adityak1911/",
//   },

//   {
//     id: 3,
//     name: "Abhay ",
//     Linkedin: "https://www.linkedin.com/in/abhay-dubey-480a48264/",
//   },
//   {
//     id: 4,
//     name: "Abhishek",
//     Linkedin: "https://www.linkedin.com/in/abhishek-sharma-38b97125b/",
//   },
//   {
//     id: 5,
//     name: "Shikhar ",
//     Linkedin: "https://www.linkedin.com/in/shikhar-shukla-011062256/",
//   },
//   {
//     id: 6,
//     name: "Vivek",
//     Linkedin:
//       "https://www.linkedin.com/company/chemical-engineering-society-svnit/mycompany/",
//   },
// ];
export const AluMillennium = {
  name: "AluMillennium",
  img: alluCar,
  design:
    "The vehicle in question employs a front-wheel drive system, wherein the power is transmitted to the front wheels. This propulsion mechanism is facilitated by the utilization of aluminum air cells, which are interconnected through a series and parallel configuration. The electrical energy generated by these air cells is then converted into mechanical energy through the utilization of a motor. This motor, in turn, drives the rotation of the wheel via a two-gear system, enabling the efficient transfer of power and the subsequent movement of the vehicle.",
  powerSource:
    "The power source utilized in this system is an Aluminum-Air Battery, which features copper electrodes connected to the aluminum components. The core structure of the cell is composed of aluminum sheets. The space between the two electrode layers is filled with a specialized material that serves a critical function within the device's overall design and operation. Potassium hydroxide (KOH) solution serves as the electrolyte. A graphite sheet coated with a paste containing activated charcoal and manganese dioxide (MnO2) functions as the cathode. Steel mesh is also attached with a cathode as a current collector. These elements are assembled together using adhesive tape, and the individual cells are connected in various series and parallel configurations to achieve the desired voltage and current output. The stacking of these electrochemical cells is facilitated through the use of an enclosure fabricated from acrylic sheets, providing a robust and organized housing for the complete power generation system.",
  stoppingMechanism:
    "The Iodine Clock is used as a stopping mechanism. Two solutions namely A and B are produced. Solution A contains fixed proportions of Starch, Water and Hydrogen Peroxide while Solution B contains fixed proportions of powdered Vitamin C, water at 323K and Iodine. These two solutions are mixed together in order to form a timed reaction",
};

export const Anerobes = {
  name: "Anerobes",
  img: aneCar,
  design:
    "The car is mounted upon by a battery of 12 volts of dimension 10cm*6.5cm*7.5 cm. The battery is charged via the Microbial Fuel Cells (MFCs) that powers the chem-e-car. The stopping mechanism consists of Arduino and a beaker of 50 mL where the stopping reaction takes place.",
  powerSource:
    "Microbial Fuel Cells (MFCs) operate based on the electrochemical activity of bacteria, converting organic matter (waste water) into electrical energy. The process begins with anaerobic bacteria in the anode chamber oxidizing organic compounds present in the substrate, releasing electrons as byproducts. These electrons travel through an external circuit connected to the anode, creating an electric current flow. A proton exchange membrane (PEM) selectively allows protons to pass through to the cathode compartment while blocking larger molecules. In the cathode chamber, oxygen or other electron acceptors react with electrons and protons to produce water, completing the electrochemical circuit. This continuous electron flow generates a steady electric current, which can be harnessed to power electrical devices or stored for later use. MFCs offer a sustainable approach to electricity generation, with applications in wastewater treatment and renewable energy production. Power Storage Device: Microbial fuel Cell produces sufficient voltage but low and fluctuating current hence low and fluctuating power. This power is not sufficient to directly run the car thus the diffused MFC power is stored to power storage devices, which when charged generates continuous and sufficiently high power. In brief, to run the Chem-e-car, the Power generated by the MFC’s is to be stored in a lead acid battery. The lead-acid battery is made of lead plates comprising of lead and lead oxide layer. The battery is then packed and charged by the source, MFC, by either one way diode switch or boost up circuit (PMS).",
  stoppingMechanism:
    "The Stopping mechanism of our car is Reaction between Sodium Thiosulfate and Hydrochloric Acid. This reaction demonstrates the formation of sodium chloride, sulfur, sulfur dioxide, and water. As the reaction Between Na2S2O3 and HCl proceeds, the formation of colloidal sulfur leads to an increase in the solution’s Turbidity. This results in a measurable decrease in the intensity of light transmitted through the mixture. Light coming from the solution Is detected and similar code is run through an Arduino which stops our circuit. Time vs Conc. Graph (Sodium Thiosulphate reacting Hydrochloric Acid) The reaction between sodium thiosulfate and hydrochloric acid is given by: 𝑁𝑎2𝑆2𝑂3 + 2𝐻𝐶𝑙 → 2𝑁𝑎𝐶𝑙 + 𝑆 + 𝑆𝑂2 + 𝐻2",
};
